version: "3"

services:
  mongodb:
    image: mongo:4.2
    container_name: "bridge_db"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./volumes/data/db:/data/db
    ports:
      - 27020:27017
    command: mongod --bind_ip_all --logpath=/dev/null
  bridge_api:
    image: mijoco/bridge_api:latest
    container_name: "bridge_api"
    environment:
      - BTC_RPC_USER=${BTC_RPC_USER}
      - BTC_RPC_PWD=${BTC_RPC_PWD}
      - BTC_NODE=${BTC_NODE}
    ports:
      - "3010:3010"
    links:
      - mongodb
